//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixel_3_Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixel_3_Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB &amp; fastboot.
        /// </summary>
        public static string AdbAndFastboot {
            get {
                return ResourceManager.GetString("AdbAndFastboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must configure settings as you are running the Toolkit for the first time..
        /// </summary>
        public static string CannotCloseOnFirstRun {
            get {
                return ResourceManager.GetString("CannotCloseOnFirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up files after flashing Factory Images..
        /// </summary>
        public static string CleanUpAfterFactoryImageFlash {
            get {
                return ResourceManager.GetString("CleanUpAfterFactoryImageFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to browse for a path. Leave empty for default values, which will be a folder called &apos;ToolkitData&apos; in the current directory..
        /// </summary>
        public static string ConfigMenuText {
            get {
                return ResourceManager.GetString("ConfigMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring settings....
        /// </summary>
        public static string ConfiguringSettings {
            get {
                return ResourceManager.GetString("ConfiguringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to Browse....
        /// </summary>
        public static string D2CtoBrowse {
            get {
                return ResourceManager.GetString("D2CtoBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading online data....
        /// </summary>
        public static string DownloadingData {
            get {
                return ResourceManager.GetString("DownloadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Platform Tools....
        /// </summary>
        public static string ExtractingPlatformTools {
            get {
                return ResourceManager.GetString("ExtractingPlatformTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Platform Tools to:.
        /// </summary>
        public static string ExtractPlatformToolsTo {
            get {
                return ResourceManager.GetString("ExtractPlatformToolsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Images:.
        /// </summary>
        public static string FactoryImagesC {
            get {
                return ResourceManager.GetString("FactoryImagesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Locations.
        /// </summary>
        public static string FileLocations {
            get {
                return ResourceManager.GetString("FileLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill ADB Server on Toolkit shutdown..
        /// </summary>
        public static string KillAdbServerOnClose {
            get {
                return ResourceManager.GetString("KillAdbServerOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magisk:.
        /// </summary>
        public static string MagiskC {
            get {
                return ResourceManager.GetString("MagiskC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magisk Custom Update URL.
        /// </summary>
        public static string MagiskCustomUrl {
            get {
                return ResourceManager.GetString("MagiskCustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up AndroidCtrl....
        /// </summary>
        public static string SettingUpAndroidCtrl {
            get {
                return ResourceManager.GetString("SettingUpAndroidCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWRP:.
        /// </summary>
        public static string TwrpC {
            get {
                return ResourceManager.GetString("TwrpC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading....
        /// </summary>
        public static string Upgrading {
            get {
                return ResourceManager.GetString("Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default.
        /// </summary>
        public static string UseDefault {
            get {
                return ResourceManager.GetString("UseDefault", resourceCulture);
            }
        }
    }
}
